// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUrlxMfytlrDL4zHdMJT-V6bpz_WuNUc',
    appId: '1:300762415901:web:08708f1a0f149bdff057f4',
    messagingSenderId: '300762415901',
    projectId: 'proyek-pertama-f873c',
    authDomain: 'proyek-pertama-f873c.firebaseapp.com',
    databaseURL: 'https://proyek-pertama-f873c-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-pertama-f873c.firebasestorage.app',
    measurementId: 'G-FTYBT39SKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRm-quK3HGwGxKuRmPz6iO3B46ZBec30',
    appId: '1:300762415901:android:a66ce8e6d871fd89f057f4',
    messagingSenderId: '300762415901',
    projectId: 'proyek-pertama-f873c',
    databaseURL: 'https://proyek-pertama-f873c-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-pertama-f873c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBicICfDPQkQYBk2Knd38sItHxQgjY2S-g',
    appId: '1:300762415901:ios:4e924bf0798cb3c5f057f4',
    messagingSenderId: '300762415901',
    projectId: 'proyek-pertama-f873c',
    databaseURL: 'https://proyek-pertama-f873c-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-pertama-f873c.firebasestorage.app',
    iosBundleId: 'com.example.cepu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBicICfDPQkQYBk2Knd38sItHxQgjY2S-g',
    appId: '1:300762415901:ios:4e924bf0798cb3c5f057f4',
    messagingSenderId: '300762415901',
    projectId: 'proyek-pertama-f873c',
    databaseURL: 'https://proyek-pertama-f873c-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-pertama-f873c.firebasestorage.app',
    iosBundleId: 'com.example.cepu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnUrlxMfytlrDL4zHdMJT-V6bpz_WuNUc',
    appId: '1:300762415901:web:a17bee9eb9ee95c3f057f4',
    messagingSenderId: '300762415901',
    projectId: 'proyek-pertama-f873c',
    authDomain: 'proyek-pertama-f873c.firebaseapp.com',
    databaseURL: 'https://proyek-pertama-f873c-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-pertama-f873c.firebasestorage.app',
    measurementId: 'G-MDCE2HWQJ3',
  );

}