// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBt43bpCl8q8pMs0VYfm72FCn7Vrkfxk',
    appId: '1:675481592085:web:a1dece0c127b657cf4891c',
    messagingSenderId: '675481592085',
    projectId: 'notes-a34a0',
    authDomain: 'notes-a34a0.firebaseapp.com',
    storageBucket: 'notes-a34a0.firebasestorage.app',
    measurementId: 'G-R7KQFYD3RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJTG6x9yBCCDdiXE_cU3n2WDRYE9NyE0',
    appId: '1:675481592085:android:d5169d06233efbf8f4891c',
    messagingSenderId: '675481592085',
    projectId: 'notes-a34a0',
    storageBucket: 'notes-a34a0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBt43bpCl8q8pMs0VYfm72FCn7Vrkfxk',
    appId: '1:675481592085:web:ccf4fba02b8947bbf4891c',
    messagingSenderId: '675481592085',
    projectId: 'notes-a34a0',
    authDomain: 'notes-a34a0.firebaseapp.com',
    storageBucket: 'notes-a34a0.firebasestorage.app',
    measurementId: 'G-NTSS9LW1XH',
  );
}
